import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,NavLink,useNavigate,useParams,useSearchParams,Navigate}from'react-router-dom';
import{createClient}from'@supabase/supabase-js';
import{Analytics}from'@vercel/analytics/react';
import{ArrowLeft,ArrowRight,Bath,BedDouble,Building2,CalendarDays,Check,CircleDollarSign,Filter,House,LogOut,Mail,MapPin,Menu,Phone,Plus,Search,ShieldCheck,X}from'lucide-react';
import'./styles.css';

const SB_URL=import.meta.env.VITE_SUPABASE_URL,SB_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=SB_URL&&SB_KEY?createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const HERO='https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2200&q=85';
const fallback=[
{id:'1',slug:'casa-luminosa-belgrano',type:'Casa',operation:'Venta',status:'Disponible',title:'Casa luminosa en Belgrano',price:385000,currency:'USD',city:'CABA',neighborhood:'Belgrano',beds:4,baths:3,area:218,parking:2,year:2018,credit:true,tag:'Destacada',description:'Casa amplia con luz natural, espacios integrados y jardín.',features:['Jardín','Parrilla','Cochera','Apto crédito'],images:['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=82','https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=82']},
{id:'2',slug:'departamento-2-ambientes-palermo',type:'Departamento',operation:'Venta',status:'Disponible',title:'Departamento 2 ambientes',price:158000,currency:'USD',city:'CABA',neighborhood:'Palermo',beds:2,baths:1,area:62,parking:0,year:2021,credit:true,tag:'Nuevo',description:'Departamento moderno y luminoso, cercano a parques y servicios.',features:['Balcón','Laundry','Apto crédito'],images:['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=82']},
{id:'3',slug:'casa-moderna-parque-nordelta',type:'Casa',operation:'Alquiler',status:'Disponible',title:'Casa moderna con parque',price:1450,currency:'USD',city:'Tigre',neighborhood:'Nordelta',beds:3,baths:2,area:240,parking:2,year:2020,credit:false,tag:'Alquiler',description:'Casa contemporánea con parque y espacios sociales generosos.',features:['Parque','Piscina','Parrilla','Cochera'],images:['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=82']},
{id:'4',slug:'duplex-terraza-villa-urquiza',type:'Departamento',operation:'Alquiler',status:'Disponible',title:'Dúplex con terraza',price:2100,currency:'USD',city:'CABA',neighborhood:'Villa Urquiza',beds:3,baths:2,area:128,parking:1,year:2019,credit:false,tag:'Disponible',description:'Dúplex con terraza propia y excelente conexión.',features:['Terraza','Cochera','Baño en suite'],images:['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=82']},
{id:'5',slug:'casa-jardin-galeria-san-isidro',type:'Casa',operation:'Venta',status:'Disponible',title:'Casa jardín y galería',price:295000,currency:'USD',city:'San Isidro',neighborhood:'Acassuso',beds:3,baths:2,area:194,parking:2,year:2016,credit:true,tag:'Destacada',description:'Casa familiar con jardín, galería y ambientes funcionales.',features:['Jardín','Galería','Cochera','Apto crédito'],images:['https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1600&q=82']},
{id:'6',slug:'vista-abierta-belgrano',type:'Departamento',operation:'Venta',status:'Disponible',title:'Vista abierta en Belgrano',price:220000,currency:'USD',city:'CABA',neighborhood:'Belgrano',beds:3,baths:2,area:118,parking:1,year:2022,credit:true,tag:'Oportunidad',description:'Departamento de tres dormitorios con vistas abiertas.',features:['Balcón','Cochera','Apto crédito'],images:['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=82']}
];

function useCatalog(filters={}){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setError('');
 (async()=>{try{let data;if(supabase){const r=await supabase.from('properties').select('*').eq('status','Disponible').order('created_at',{ascending:false});if(r.error)throw r.error;data=(r.data||[]).map(p=>({...p,beds:p.bedrooms,baths:p.bathrooms,credit:p.credit_eligible,images:p.images||[],features:p.features||[]}));}else data=fallback;
 data=data.filter(p=>(!filters.operation||p.operation===filters.operation)&&(!filters.type||p.type===filters.type)&&(!filters.q||`${p.title} ${p.city} ${p.neighborhood}`.toLowerCase().includes(filters.q.toLowerCase()))&&(!filters.max||p.price<=Number(filters.max))&&(!filters.beds||p.beds>=Number(filters.beds))&&(!filters.credit||p.credit));
 if(alive)setItems(data);
 }catch(e){if(alive)setError(e.message||'No pudimos cargar el catálogo.')}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[JSON.stringify(filters)]);
 return{items,loading,error};
}

function Layout({children}){return <><Header/>{children}<Footer/></>}
function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><div className="container header-inner"><Link className="brand" to="/" onClick={()=>setOpen(false)}><span className="brand-mark"><Building2 size={21}/></span>Grupo Meridiano</Link><nav className={open?'desktop-nav mobile-open':'desktop-nav'}>{[['/','Inicio'],['/comprar','Comprar'],['/alquilar','Alquilar'],['/propiedades','Propiedades'],['/contacto','Contacto']].map(([to,label])=><NavLink key={to} to={to} end={to==='/' } onClick={()=>setOpen(false)}>{label}</NavLink>)}</nav><Link className="outline-btn header-cta" to="/admin">Trastienda</Link><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X size={22}/>:<Menu size={22}/>}</button></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><Link className="brand footer-brand" to="/"><span className="brand-mark"><Building2 size={18}/></span>Grupo Meridiano</Link><p>Más de 20 años acompañando a familias e inversores a encontrar su próximo lugar en Buenos Aires.</p></div><div><h4>Navegación</h4><Link to="/">Inicio</Link><Link to="/propiedades">Propiedades</Link><Link to="/contacto">Contacto</Link></div><div><h4>Contacto</h4><span>Av. del Libertador 1234, CABA</span><span>+54 11 4000-0000</span><span>hola@grupomeridiano.com.ar</span></div></div></footer>}
function Home(){const[op,setOp]=useState('Venta'),[type,setType]=useState(''),[q,setQ]=useState('');const query=new URLSearchParams({...(q?{q}:{}),...(type?{type}:{})}).toString();return <Layout><section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(12,90,69,.93),rgba(12,90,69,.45)),url(${HERO})`}}><div className="container hero-content"><div className="eyebrow">Venta y alquiler en Buenos Aires</div><h1>Encontrá el lugar donde<br/>empieza tu próxima historia</h1><p>Una selección curada de propiedades en las mejores zonas.<br/>Comprar o alquilar nunca fue tan simple.</p><div className="searchbar"><select value={op} onChange={e=>setOp(e.target.value)}><option value="Venta">Comprar</option><option value="Alquiler">Alquilar</option></select><select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos los tipos</option><option value="Casa">Casa</option><option value="Departamento">Departamento</option></select><div className="search-input"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Barrio, ciudad o palabra clave"/></div><Link className="search-btn" to={`/${op==='Venta'?'comprar':'alquilar'}${query?'?'+query:''}`}><Search size={17}/>Buscar</Link></div></div></section><div className="stats container"><Stat v="7.000+" l="Propiedades activas" i={<House size={18}/>}/><Stat v="1.200+" l="Operaciones cerradas" i={<CircleDollarSign size={18}/>}/><Stat v="20 años" l="En el mercado" i={<CalendarDays size={18}/>}/><Stat v="100%" l="Atención personalizada" i={<ShieldCheck size={18}/>}/></div><section className="section container"><div className="section-head"><div><span className="section-kicker">SELECCIÓN CURADA</span><h2>Propiedades para vos</h2></div><Link className="text-btn" to="/propiedades">Ver todas <ArrowRight size={16}/></Link></div><div className="property-grid">{fallback.slice(0,3).map(p=><Card key={p.id} p={p}/>)}</div></section><section className="green-cta container"><div><span className="section-kicker light">ESTAMOS PARA AYUDARTE</span><h2>¿Querés vender o alquilar tu propiedad?</h2><p>Te acompañamos en todo el proceso, desde la tasación hasta la entrega de llaves.</p></div><Link className="white-solid-btn" to="/vender">Contar con nosotros <ArrowRight size={16}/></Link></section></Layout>}
function Stat({v,l,i}){return <div className="stat"><span className="stat-icon">{i}</span><div><strong>{v}</strong><span>{l}</span></div></div>}
function Card({p}){const price=p.priceFormatted||`$ ${Number(p.price).toLocaleString('es-AR')}${p.operation==='Alquiler'?' / mes':''}`;const city=p.city==='CABA'&&p.neighborhood?p.neighborhood+', CABA':p.city;return <article className="property-card"><div className="image-wrap"><img src={p.images?.[0]||p.image} alt={p.title}/><span className="pill">{p.tag||p.status}</span></div><div className="card-body"><div className="price-row"><strong>{price}</strong><span>{p.operation}</span></div><h3>{p.title}</h3><p className="location"><MapPin size={15}/>{city}</p><div className="meta"><span><BedDouble size={15}/>{p.beds} hab.</span><span><House size={15}/>{p.baths} baños</span><span>{p.area} m²</span></div></div></article>}
function Properties({fixedOperation=''}){const[params,setParams]=useSearchParams();const initial={operation:params.get('operation')||fixedOperation,type:params.get('type')||'',q:params.get('q')||''};const[op,setOp]=useState(initial.operation),[type,setType]=useState(initial.type||'Todos'),[q,setQ]=useState(initial.q);const list=fallback.filter(p=>(!op||p.operation===op)&&(type==='Todos'||!type||p.type===type)&&(!q||`${p.title} ${p.city} ${p.neighborhood}`.toLowerCase().includes(q.toLowerCase())));return <Layout><section className="section container properties-page"><div className="page-title"><span className="section-kicker">PROPIEDADES</span><h1>Encontrá tu próximo lugar</h1><p>{list.length} propiedades encontradas · filtros simples, decisiones claras.</p></div><div className="filter-bar"><div className="field"><label>Buscar</label><div className="field-input"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Palermo, Belgrano..."/></div></div><div className="field"><label>Operación</label><select value={op} onChange={e=>setOp(e.target.value)}><option value="">Todas</option><option>Venta</option><option>Alquiler</option></select></div><div className="field"><label>Tipo</label><select value={type} onChange={e=>setType(e.target.value)}><option>Todos</option><option>Casa</option><option>Departamento</option></select></div><div className="field"><label>Precio</label><select><option>Sin límite</option><option>Hasta $200.000</option><option>Hasta $400.000</option></select></div><button className="green-solid-btn filter-btn" type="button"><Filter size={16}/>Aplicar filtros</button></div><div className="results-head"><span>{list.length} propiedades encontradas</span><button className="sort-btn" type="button">Más recientes <ChevronDown size={16}/></button></div><div className="property-grid four">{list.map(p=><Card key={p.id} p={p}/>)}</div>{!list.length&&<div className="empty"><Sparkles size={24}/><h3>No encontramos coincidencias</h3><p>Probá con otros filtros y seguimos buscando.</p></div>}</section></Layout>}
function Field({label,children}){return <div className="field"><label>{label}</label>{children}</div>}

function Detail(){const{slug}=useParams();const[loading,setLoading]=useState(true),[p,setP]=useState(null),[error,setError]=useState('');useEffect(()=>{(async()=>{try{if(supabase){const r=await supabase.from('properties').select('*').eq('slug',slug).maybeSingle();if(r.error)throw r.error;setP(r.data&&({...r.data,beds:r.data.bedrooms,baths:r.data.bathrooms,credit:r.data.credit_eligible}));}else setP(fallback.find(x=>x.slug===slug)||null)}catch(e){setError(e.message)}finally{setLoading(false)}})()},[slug]);if(loading)return <div className="state-page">Cargando propiedad…</div>;if(error)return <div className="state-page"><h1>No pudimos cargar la propiedad</h1><p>{error}</p></div>;if(!p)return <Layout><div className="state-page"><h1>Propiedad no encontrada</h1><Link to="/propiedades">Volver al catálogo</Link></div></Layout>;return <Layout><main className="detail-page container"><Link className="back-link" to="/propiedades"><ArrowLeft size={16}/>Volver a propiedades</Link><div className="gallery">{p.images.map((img,i)=><img key={img} src={img} alt={i?'':'Foto principal de '+p.title} width="1600" height="1000" loading={i?'lazy':undefined}/>)}</div><div className="detail-grid"><article><span className="section-kicker">{p.operation} · {p.status}</span><h1>{p.title}</h1><p className="location"><MapPin size={16}/>{p.neighborhood}, {p.city}</p><div className="detail-meta"><span><BedDouble/> {p.beds} dormitorios</span><span><Bath/> {p.baths} baños</span><span><House/> {p.area} m²</span></div><p className="detail-description">{p.description}</p><h2>Características</h2><ul className="feature-list">{(p.features||[]).map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul></article><aside className="detail-cta"><strong>{p.currency} {Number(p.price).toLocaleString('es-AR')}</strong><span>{p.operation}</span><Link className="green-solid-btn" to={`/contacto?property=${encodeURIComponent(p.title)}`}>Consultar esta propiedad</Link><small>La ubicación exacta y condiciones comerciales se confirman con el equipo.</small></aside></div></main></Layout>}

function Contact(){const[sent,setSent]=useState(false);return <Layout><section className="section container contact-page"><div className="page-title"><span className="section-kicker">HABLEMOS</span><h1>Contacto</h1><p>¿Buscás una propiedad o querés que tasemos la tuya? Escribinos.</p></div><div className="contact-grid"><div><Info i={<Building2 size={18}/>}t="Oficina"d="Av. del Libertador 1234, CABA"/><Info i={<Phone size={18}/>}t="Teléfono"d="+54 11 4000-0000"/><Info i={<Mail size={18}/>}t="Email"d="hola@grupomeridiano.com.ar"/><Info i={<CalendarDays size={18}/>}t="Horario"d="Lun a Vie · 9 a 18 hs"/></div><form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-head"><div><span className="section-kicker">ESCRIBINOS</span><h2>Contanos qué necesitás</h2></div><span className="form-badge">Respuesta en el día</span></div><div className="two-col"><label>Tu nombre<input required placeholder="Nombre y apellido"/></label><label>Teléfono<input required placeholder="+54 11..."/></label></div><div className="two-col"><label>Email<input required type="email" placeholder="tu@email.com"/></label><label>Asunto<select><option>Quiero comprar</option><option>Quiero alquilar</option><option>Quiero vender</option></select></label></div><label>Mensaje<textarea rows="6" placeholder="Contanos qué estás buscando..."/></label><button className="green-solid-btn submit-btn" type="submit">{sent?<><Check size={17}/>Mensaje enviado</>:<>Enviar consulta <ArrowRight size={17}/></>}</button></form></div></section></Layout>}
function Info({i,t,d}){return <div className="contact-item"><span>{i}</span><div><strong>{t}</strong><p>{d}</p></div></div>}

function Sell(){return <Layout><section className="section container sell-page"><div className="sell-card"><div className="sell-copy"><span className="section-kicker light">TRASTIENDA</span><h1>Tu propiedad merece una estrategia, no un aviso más.</h1><p>Te acompañamos con tasación, publicación, visitas y negociación. Todo en un mismo equipo.</p><Link className="white-solid-btn" to="/contacto">Quiero una tasación <ArrowRight size={17}/></Link></div><div className="sell-side"><div><strong>20</strong><span>años de experiencia</span></div><div><strong>1.200+</strong><span>operaciones cerradas</span></div><div><strong>4,9/5</strong><span>satisfacción</span></div></div></div></section></Layout>}
function Login(){const nav=useNavigate(),[email,setEmail]=useState(''),[pw,setPw]=useState(''),[error,setError]=useState('');if(!supabase)return <main className="auth-page"><div className="auth-card"><h1>Backend no configurado</h1><p>Definí VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY para habilitar el panel.</p></div></main>;return <main className="auth-page"><form className="auth-card" onSubmit={async e=>{e.preventDefault();setError('');const r=await supabase.auth.signInWithPassword({email,password:pw});if(r.error)setError(r.error.message);else nav('/admin')}}><span className="section-kicker">TRASTIENDA</span><h1>Acceso comercial</h1><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input required type="password" value={pw} onChange={e=>setPw(e.target.value)}/></label>{error&&<div className="error-box" role="alert">{error}</div>}<button className="green-solid-btn">Ingresar</button></form></main>}

function Admin(){return <section className="panel-wrap"><aside className="panel-sidebar"><div className="panel-logo"><span className="brand-mark"><Building2 size={20}/></span><div><strong>Grupo Meridiano</strong><small>Panel inmobiliario</small></div></div>{['Resumen','Propiedades','Consultas','Contactos','Contenido'].map((x,i)=><button key={x} className={i===0?'panel-link active':'panel-link'} type="button">{x}</button>)}<div className="sidebar-spacer"/><button className="panel-link" type="button">Cerrar sesión</button></aside><div className="panel-main"><div className="panel-top"><div><span className="section-kicker">PANEL</span><h1>Resumen de tu inmobiliaria</h1></div><button className="green-solid-btn" type="button">＋ Nueva propiedad</button></div><div className="metric-grid"><Stat v="7" l="Propiedades" i={<House size={17}/>}/><Stat v="4" l="En venta" i={<CircleDollarSign size={17}/>}/><Stat v="3" l="En alquiler" i={<CalendarDays size={17}/>}/><Stat v="2" l="Consultas nuevas" i={<Mail size={17}/>}/></div><div className="dashboard-grid"><div className="dashboard-card"><div className="card-head"><h3>Últimas propiedades</h3></div>{fallback.slice(0,4).map((p,i)=><div className="dash-row" key={p.id}><div className="dash-avatar">{i+1}</div><div><strong>{p.title}</strong><span>{`$ ${Number(p.price).toLocaleString('es-AR')}${p.operation==='Alquiler'?' / mes':''}`}</span></div><span className="row-badge">Disponible</span></div>)}</div><div className="dashboard-card"><div className="card-head"><h3>Últimas consultas</h3></div>{['Mariana A. · Departamento en Palermo','Lucas F. · Casa en Nordelta','Sofía R. · Casa para compra','Pablo M. · Tasación de propiedad'].map((x,i)=><div className="dash-row" key={x}><div className="dash-avatar">{i+1}</div><div><strong>{x.split(' · ')[0]}</strong><span>{x.split(' · ')[1]}</span></div><span className="row-badge">{i%2?'Respondida':'Pendiente'}</span></div>)}</div></div></div></section>}
function Privacy(){return <Layout><section className="section container"><span className="section-kicker">PRIVACIDAD</span><h1>Política de privacidad</h1><p>Reemplazar este contenido por el texto legal definitivo antes de producción.</p></section></Layout>}
function NotFound(){return <main className="state-page"><span className="section-kicker">404</span><h1>Página no encontrada</h1><Link className="green-solid-btn" to="/">Volver al inicio</Link></main>}

function App(){return <BrowserRouter><Analytics/><Routes><Route path="/" element={<Home/>}/><Route path="/propiedades" element={<Properties/>}/><Route path="/propiedades/:slug" element={<Detail/>}/><Route path="/comprar" element={<Properties fixedOperation="Venta"/>}/><Route path="/alquilar" element={<Properties fixedOperation="Alquiler"/>}/><Route path="/contacto" element={<Contact/>}/><Route path="/vender" element={<Sell/>}/><Route path="/admin/login" element={<Login/>}/><Route path="/admin" element={<Admin/>}/><Route path="/politica-privacidad" element={<Privacy/>}/><Route path="*" element={<NotFound/>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);